### ISSUE TITLE
PWM on speed controller

### ISSUE THREAD

**Issue by wujiang** [grassjelly/lino_docs#1]
Thank you very much for the documentation! It helps a lot. I'm a little confused about how the speed controller gets PWM signal from teensy. Is the ENA pin also a PWM pin? I'm trying to use VNH5019 instead. If you have a schematic for VNH5019 it will be great. Thank you!

**Comment by grassjelly** [comment]
Hey there,

You may try using this diagram. Connect the driver's PWM pin(M1PWM) to Teensy's PWM pin (ie MOTOR1_PWM) https://github.com/grassjelly/linorobot/blob/master/arduino/firmware/lib/config/lino_base_config.h#L37



I haven't tried this driver but it should work. Hope this help.

**Comment by wujiang** [comment]
Understood. Confirmed ENA and ENB connect to PWM. Thank you! Closing.
